packageExtensions:
  "@storybook/addon-doc@*":
    peerDependencies:
      sass: "*"
  "@storybook/addon-storyshots@*":
    peerDependencies:
      "@storybook/react": "*"
  "@storybook/core@*":
    peerDependencies:
      sass: "*"
  "@storybook/react@*":
    peerDependencies:
      sass: "*"
  next@*:
    peerDependencies:
      sass: "*"
  sass-loader@*:
    peerDependencies:
      sass: "*"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
